# status only
esphome:
  name: k5
  platform: ESP8266
  board: nodemcuv2

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd

api:

ota:
  safe_mode: true
  password: !secret ota

binary_sensor:
  - platform: status
    name: "k5_status"
